name: Build Starter Template on Change

on:
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'templates/starter/**'
  pull_request:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'templates/starter/**'

jobs:
  call-reusable-build:
    uses: ./.github/workflows/build-starter-template.yml
