name: Test Nix Flake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nixos-build:
    runs-on: ubuntu-latest
    name: Build NixOS Configuration
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13

    - name: Build NixOS Flake
      run: |
        ls -la
        cat ./flake.nix
        nix build --extra-experimental-features 'nix-command flakes' --no-link --keep-going --option extra-sandbox-paths / --impure .#nixosConfigurations."x86_64-linux".config.system.build.toplevel


  darwin-build:
    runs-on: ubuntu-latest
    name: Build nix-darwin Configuration
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13

    - name: Build nix-darwin Flake
      run: |
        ls -la
        cat ./flake.nix
        nix build --extra-experimental-features 'nix-command flakes' --no-link --keep-going --option extra-sandbox-paths / --impure .#darwinConfigurations."Dustins-MBP".system

